name: resonance
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib >=2.1
  - numpy >=1.13
  - pandas >=0.17
  - python >=3.6
  - resonance
  - scipy >=0.19
  - sympy >=1.1
  - ipympl >=0.5.7
